# Site settings
author: Olusola Olagoroye
title: #Becoming  a Developer".
header-img: img/home-bg.png
email: solaolagoroye@gmail.com
copyright_name: Olusola Olagoroye
description: > # this means to ignore newlines until "baseurl:"
  Making a Change and Loving the Big Picture
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  olagoroye

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
